<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analytics 101 -- Exploratory Data Analysis using R. – livecase01</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analytics 101 – Exploratory Data Analysis using R.</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/" rel="" target="_blank"><i class="bi bi-globe" role="img">
</i> 
 <span class="menu-text">Sameer Mathur</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/SameerMathur/DataAnalytics101" rel="" target="_blank"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Book’s Github</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17LiveCase01.html">Live Case: Overview of the S&amp;P500</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/openscapes_hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01GettingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring R programming</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02RPackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring R Packages</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03DataStructures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring Data Structures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04ReadingData.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading Data into R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05ExploringDataframes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring Dataframes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06ExploringTibbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring <em>tibbles</em> &amp; <em>dplyr</em></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07CategoricalData01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Univariate Categorical data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08CategoricalData02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Categorical data (Part 1 of 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09CategoricalData03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Categorical data (Part 2 of 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10ContinuousData01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Univariate Continuous data (Part 1 of 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11ContinuousData02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Univariate Continuous data (Part 2 of 2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12ContinuousData03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Continuous data (Part 1 of 4)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13ContinuousData04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Continuous data (Part 2 of 4)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14ContinuousData05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Continuous data (Part 3 of 4)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15ContinuousData06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate Continuous data (Part 4 of 4)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16ThreeDimensions01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Three Dimensional (3D) Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17LiveCase01.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Live Case: Overview of the S&amp;P500</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18LiveCaseREIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Live Case (2): REITs in the S&amp;P500</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="BookCover101.png" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#live-case-overview-of-the-sp500" id="toc-live-case-overview-of-the-sp500" class="nav-link active" data-scroll-target="#live-case-overview-of-the-sp500">Live Case: Overview of the S&amp;P500</a>
  <ul class="collapse">
  <li><a href="#sp-500" id="toc-sp-500" class="nav-link" data-scroll-target="#sp-500">S&amp;P 500</a></li>
  <li><a href="#sp-500-data" id="toc-sp-500-data" class="nav-link" data-scroll-target="#sp-500-data">S&amp;P 500 Data</a>
  <ul class="collapse">
  <li><a href="#load-some-useful-r-packages" id="toc-load-some-useful-r-packages" class="nav-link" data-scroll-target="#load-some-useful-r-packages">Load some useful R packages</a></li>
  <li><a href="#read-the-sp500-data-from-a-google-sheet-into-a-tibble" id="toc-read-the-sp500-data-from-a-google-sheet-into-a-tibble" class="nav-link" data-scroll-target="#read-the-sp500-data-from-a-google-sheet-into-a-tibble">Read the S&amp;P500 data from a Google Sheet into a tibble</a></li>
  </ul></li>
  <li><a href="#sp-global-industry-classification-standard-gics" id="toc-sp-global-industry-classification-standard-gics" class="nav-link" data-scroll-target="#sp-global-industry-classification-standard-gics">S&amp;P Global Industry Classification Standard (GICS<sup>®</sup>)</a></li>
  <li><a href="#loading-the-data-into-r" id="toc-loading-the-data-into-r" class="nav-link" data-scroll-target="#loading-the-data-into-r">Loading the data into R</a></li>
  <li><a href="#review-the-sp-500-data" id="toc-review-the-sp-500-data" class="nav-link" data-scroll-target="#review-the-sp-500-data">Review the S&amp;P 500 data</a>
  <ul class="collapse">
  <li><a href="#rename-data-columns" id="toc-rename-data-columns" class="nav-link" data-scroll-target="#rename-data-columns">Rename Data Columns</a></li>
  <li><a href="#understand-the-data-columns" id="toc-understand-the-data-columns" class="nav-link" data-scroll-target="#understand-the-data-columns">Understand the Data Columns</a></li>
  <li><a href="#stock-ratings" id="toc-stock-ratings" class="nav-link" data-scroll-target="#stock-ratings">Stock Ratings</a></li>
  <li><a href="#analysis-of-gics-sectors-in-the-sp500" id="toc-analysis-of-gics-sectors-in-the-sp500" class="nav-link" data-scroll-target="#analysis-of-gics-sectors-in-the-sp500">Analysis of GICS Sectors in the S&amp;P500</a></li>
  <li><a href="#marketcap-by-gics-sector" id="toc-marketcap-by-gics-sector" class="nav-link" data-scroll-target="#marketcap-by-gics-sector">MarketCap by GICS Sector</a></li>
  </ul></li>
  <li><a href="#summary-of-chapter-exploring-sp500-data" id="toc-summary-of-chapter-exploring-sp500-data" class="nav-link" data-scroll-target="#summary-of-chapter-exploring-sp500-data">Summary of Chapter – Exploring S&amp;P500 Data</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="17LiveCase01.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="live-case-overview-of-the-sp500" class="level1">
<h1>Live Case: Overview of the S&amp;P500</h1>
<p><strong>Chapter 17, <em>Last updated: Jan 05, 2024</em></strong></p>
<section id="sp-500" class="level2">
<h2 class="anchored" data-anchor-id="sp-500">S&amp;P 500</h2>
<p>The S&amp;P 500, also called the Standard &amp; Poor’s 500, is a stock market index that tracks the performance of 500 major publicly traded companies listed on U.S. stock exchanges. It serves as a widely accepted benchmark for assessing the overall health and performance of the U.S. stock market.</p>
<p>S&amp;P Dow Jones Indices, a division of S&amp;P Global, is responsible for maintaining the index. The selection of companies included in the S&amp;P 500 is determined by a committee, considering factors such as market capitalization, liquidity, and industry representation.</p>
<p>The S&amp;P is a float-weighted index, meaning the market capitalizations of the companies in the index are adjusted by the number of shares available for public trading. [1]</p>
<p>The performance of the S&amp;P 500 is frequently used to gauge the broader stock market and is commonly referenced by investors, analysts, and financial media. It provides a snapshot of how large-cap U.S. stocks are faring and is considered a reliable indicator of overall market sentiment.</p>
<p>Typically, the S&amp;P 500 index consists of 500 stocks. However, in reality, there are actually 503 stocks included. This discrepancy arises because three of the listed companies have multiple share classes, and each class is considered a separate stock that needs to be included in the index.</p>
<p><strong>Strengths</strong>:</p>
<ol type="1">
<li><p><strong>Diverse Representation</strong>: The S&amp;P 500 isn’t fixated on a single industry. From technology to healthcare, it offers a panoramic view of various economic sectors, making it an inclusive representation of the U.S. corporate sector.</p></li>
<li><p><strong>Benchmark for Investors</strong>: For many fund managers, outperforming the S&amp;P 500 stands as a golden standard. It’s a yardstick, establishing it as a critical touchstone for gauging investment success.</p></li>
<li><p><strong>Liquidity and Visibility</strong>: Constituent companies enjoy high liquidity and are subject to rigorous screening processes, ensuring that the index represents financially viable entities.</p></li>
</ol>
<p><strong>Critiques</strong>:</p>
<ol type="1">
<li><p><strong>Market Capitalization Weighting</strong>: The index is weighted by market capitalization, meaning companies with higher market values have a more pronounced effect on its performance. Critics argue this approach can skew perceptions, especially during market bubbles when certain sectors are overvalued.</p></li>
<li><p><strong>Exclusivity</strong>: Despite its broad purview, 500 companies cannot encapsulate the entire U.S. economy. Many sectors, especially emerging industries or smaller businesses, might not be adequately represented.</p></li>
<li><p><strong>Potential for Complacency</strong>: The prominence of the S&amp;P 500 has led many investors to adopt passive investment strategies, tracking the index rather than actively managing portfolios. Detractors argue this might lead to market inefficiencies and reduced capital allocation efficacy.</p></li>
</ol>
<p>While the S&amp;P 500 remains an influential and pivotal tool for investors, its dominance prompts a double-edged sword of advantages and critiques. In a constantly evolving economic landscape, understanding both its power and limitations is essential for informed financial decision-making. [2]</p>
</section>
<section id="sp-500-data" class="level2">
<h2 class="anchored" data-anchor-id="sp-500-data">S&amp;P 500 Data</h2>
<section id="load-some-useful-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="load-some-useful-r-packages">Load some useful R packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the required libraries, suppressing annoying startup messages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For data manipulation</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For data manipulation</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For data visualization</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For data visualization</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For Google Sheets</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rmarkdown, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For writing</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For tables</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>) <span class="co"># For tables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-the-sp500-data-from-a-google-sheet-into-a-tibble" class="level3">
<h3 class="anchored" data-anchor-id="read-the-sp500-data-from-a-google-sheet-into-a-tibble">Read the S&amp;P500 data from a Google Sheet into a tibble</h3>
<ol type="1">
<li><p>We will analyze a real-world, recent dataset containing information about the S&amp;P500 stocks, sourced from TradingView.com. [3]</p></li>
<li><p>The dataset is located in a <a href="https://docs.google.com/spreadsheets/d/14mUlNNpeuV2RouT9MKaAWKUpvjRijzQu40DdWJgyKPQ/" target="_blank">Google Sheet</a> and periodically updated.</p></li>
<li><p>The complete URL of the Google Sheet that has the data is</p>
<p><a href="https://docs.google.com/spreadsheets/d/14mUlNNpeuV2RouT9MKaAWKUpvjRijzQu40DdWJgyKPQ/" class="uri">https://docs.google.com/spreadsheets/d/14mUlNNpeuV2RouT9MKaAWKUpvjRijzQu40DdWJgyKPQ/</a></p></li>
<li><p>Notice that the Google Sheet ID is: <code>14mUlNNpeuV2RouT9MKaAWKUpvjRijzQu40DdWJgyKPQ</code>.</p></li>
</ol>
</section>
</section>
<section id="sp-global-industry-classification-standard-gics" class="level2">
<h2 class="anchored" data-anchor-id="sp-global-industry-classification-standard-gics">S&amp;P Global Industry Classification Standard (GICS<sup>®</sup>)</h2>
<p>In this case study, we will classify and analyze the S&amp;P 500 stocks based on the GICS standard.</p>
<p>The Global Industry Classification Standard (GICS<sup>®</sup>) was developed in 1999 by S&amp;P Dow Jones Indices and MSCI. The GICS methodology aims to enhance the investment research and asset management process for financial professionals worldwide. The GICS methodology has been widely accepted as an industry analysis framework for investment research, portfolio management and asset allocation. Its universal approach to industries worldwide has contributed to transparency and efficiency in the investment process, and the GICS methodology supports the trend towards sector-based investing. [4]</p>
<p>The GICS classification consists of <strong>11</strong>&nbsp;sectors, <strong>25</strong>&nbsp;industry groups. The 11 sectors are {Communication Services, Consumer Discretionary, Consumer Staples, Energy, Financials, Health Care, Industrials, Information Technology, Materials, Real Estate, Utilities}. The classificaiton of each stock in the S&amp;P 500 according to GICS is available at the following Google Sheet:</p>
<p><a href="https://docs.google.com/spreadsheets/d/1WrVA8dPYvQsc_mXVctgTntRLS02qd7ubzcdAsw03Lgk/edit#gid=0" class="uri">https://docs.google.com/spreadsheets/d/1WrVA8dPYvQsc_mXVctgTntRLS02qd7ubzcdAsw03Lgk/edit#gid=0</a></p>
<p>Again, we note that the Google Sheet ID is <code>1WrVA8dPYvQsc_mXVctgTntRLS02qd7ubzcdAsw03Lgk</code></p>
</section>
<section id="loading-the-data-into-r" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data-into-r">Loading the data into R</h2>
<p>We will connect to both these Google Sheets and read the data into a tibble. We can use the function <code>gsheet2tbl</code> in package <code>gsheet</code> to read the Google Sheet into a tibble , as demonstrated in the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read S&amp;P500 stock data present in a Google Sheet.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>prefix <span class="ot">&lt;-</span> <span class="st">"https://docs.google.com/spreadsheets/d/"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>sheetID <span class="ot">&lt;-</span> <span class="st">"14mUlNNpeuV2RouT9MKaAWKUpvjRijzQu40DdWJgyKPQ"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>url500 <span class="ot">&lt;-</span> <span class="fu">paste</span>(prefix,sheetID) <span class="co"># Form the URL to connect to</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>sp500Data <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(url500) <span class="co"># Read it into a tibble called sp500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li><strong>Reference</strong>: This data has is current as of <strong>5Jan2024</strong></li>
</ol>
<p>Similarly, we can also read the GICS classification.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read GICS classificaiton of S&amp;P 500 stocks from a Google Sheet.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>prefix2 <span class="ot">&lt;-</span> <span class="st">"https://docs.google.com/spreadsheets/d/"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>sheetID2 <span class="ot">&lt;-</span> <span class="st">"1WrVA8dPYvQsc_mXVctgTntRLS02qd7ubzcdAsw03Lgk"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>urlgics <span class="ot">&lt;-</span> <span class="fu">paste</span>(prefix2, sheetID2) <span class="co"># Form the URL to connect to</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>gics <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(urlgics) <span class="co"># Read it into a tibble called sp500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We join the two tibbles, using “Stock” as the key and name our joint tibble “sp500”. For this purpose, we can write the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merging dataframes</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sp500 <span class="ot">&lt;-</span> <span class="fu">merge</span>(sp500Data, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>               gics , </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">id =</span> <span class="st">"Stock"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="review-the-sp-500-data" class="level2">
<h2 class="anchored" data-anchor-id="review-the-sp-500-data">Review the S&amp;P 500 data</h2>
<ol type="1">
<li>The data corresponds to 503 companies that are part of the S&amp;P500 and includes 39 data columns.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sp500)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 503  39</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>The first ten stocks in the S&amp;P500 data, their GICS Sector and their recent prices are as follows:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(sp500$`GICS Sector`)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>sp500 <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Stock, Description, GICSSector, Date, Price) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"The first 10 companies in the S&amp;P500 dataset"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>The first 10 companies in the S&amp;P500 dataset</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Stock</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">GICSSector</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Date</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Agilent Technologies, Inc.</td>
<td style="text-align: left;">Health Care</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">131.1500</td>
</tr>
<tr class="even">
<td style="text-align: left;">AAL</td>
<td style="text-align: left;">American Airlines Group, Inc.</td>
<td style="text-align: left;">Industrials</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">13.3297</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AAPL</td>
<td style="text-align: left;">Apple Inc.</td>
<td style="text-align: left;">Information Technology</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">182.0300</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABBV</td>
<td style="text-align: left;">AbbVie Inc.</td>
<td style="text-align: left;">Health Care</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">162.1400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ABNB</td>
<td style="text-align: left;">Airbnb, Inc.</td>
<td style="text-align: left;">Consumer Discretionary</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">135.1750</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABT</td>
<td style="text-align: left;">Abbott Laboratories</td>
<td style="text-align: left;">Health Care</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">110.4500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACGL</td>
<td style="text-align: left;">Arch Capital Group Ltd.</td>
<td style="text-align: left;">Financials</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">77.7459</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACN</td>
<td style="text-align: left;">Accenture plc</td>
<td style="text-align: left;">Information Technology</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">339.1400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ADBE</td>
<td style="text-align: left;">Adobe Inc.</td>
<td style="text-align: left;">Information Technology</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">567.6200</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADI</td>
<td style="text-align: left;">Analog Devices, Inc.</td>
<td style="text-align: left;">Information Technology</td>
<td style="text-align: left;">5Jan2024</td>
<td style="text-align: right;">185.7200</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="3" type="1">
<li>Data Columns</li>
</ol>
<ul>
<li>The data comprises of the following 39 columns:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sp500) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Stock"                                  
 [2] "Date"                                   
 [3] "Description"                            
 [4] "Sector"                                 
 [5] "Industry"                               
 [6] "Market Capitalization"                  
 [7] "Price"                                  
 [8] "52 Week Low"                            
 [9] "52 Week High"                           
[10] "Return on Equity (TTM)"                 
[11] "Return on Assets (TTM)"                 
[12] "Return on Invested Capital (TTM)"       
[13] "Gross Margin (TTM)"                     
[14] "Operating Margin (TTM)"                 
[15] "Net Margin (TTM)"                       
[16] "Price to Earnings Ratio (TTM)"          
[17] "Price to Book (FY)"                     
[18] "Enterprise Value/EBITDA (TTM)"          
[19] "EBITDA (TTM)"                           
[20] "EPS Diluted (TTM)"                      
[21] "EBITDA (TTM YoY Growth)"                
[22] "EBITDA (Quarterly YoY Growth)"          
[23] "EPS Diluted (TTM YoY Growth)"           
[24] "EPS Diluted (Quarterly YoY Growth)"     
[25] "Price to Free Cash Flow (TTM)"          
[26] "Free Cash Flow (TTM YoY Growth)"        
[27] "Free Cash Flow (Quarterly YoY Growth)"  
[28] "Debt to Equity Ratio (MRQ)"             
[29] "Current Ratio (MRQ)"                    
[30] "Quick Ratio (MRQ)"                      
[31] "Dividend Yield Forward"                 
[32] "Dividends per share (Annual YoY Growth)"
[33] "Price to Sales (FY)"                    
[34] "Revenue (TTM YoY Growth)"               
[35] "Revenue (Quarterly YoY Growth)"         
[36] "Technical Rating"                       
[37] "Security"                               
[38] "GICSSector"                             
[39] "GICSSubIndustry"                        </code></pre>
</div>
</div>
<ul>
<li>The names of the data columns are self-explanatory. The Financial terms are explained in depth on multiple external websites such as www.Investopedia.com</li>
</ul>
<section id="rename-data-columns" class="level3">
<h3 class="anchored" data-anchor-id="rename-data-columns">Rename Data Columns</h3>
<ol start="4" type="1">
<li>The names of the data columns are lengthy and confusing. We will rename the data columns to make it easier to work with the data.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a mapping of new column names</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>new_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Stock"</span>, <span class="st">"Date"</span>, <span class="st">"StockName"</span>, <span class="st">"Sector"</span>, <span class="st">"Industry"</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MarketCap"</span>, <span class="st">"Price"</span>, <span class="st">"Low52Wk"</span>, <span class="st">"High52Wk"</span>, </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ROE"</span>, <span class="st">"ROA"</span>, <span class="st">"ROIC"</span>, <span class="st">"GrossMargin"</span>, </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"OperatingMargin"</span>, <span class="st">"NetMargin"</span>, <span class="st">"PE"</span>, </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"PB"</span>, <span class="st">"EVEBITDA"</span>, <span class="st">"EBITDA"</span>, <span class="st">"EPS"</span>, </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EBITDA_YOY"</span>, <span class="st">"EBITDA_QYOY"</span>, <span class="st">"EPS_YOY"</span>, </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"EPS_QYOY"</span>, <span class="st">"PFCF"</span>, <span class="st">"FCF"</span>, </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FCF_QYOY"</span>, <span class="st">"DebtToEquity"</span>, <span class="st">"CurrentRatio"</span>, </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"QuickRatio"</span>, <span class="st">"DividendYield"</span>, </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DividendsPerShare_YOY"</span>, <span class="st">"PS"</span>, </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Revenue_YOY"</span>, <span class="st">"Revenue_QYOY"</span>, <span class="st">"Rating"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Security"</span>, <span class="st">"GICSSector"</span>, <span class="st">"GICSSubIndustry"</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns using the new_names vector</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sp500)<span class="ot">&lt;-</span>new_names</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" type="1">
<li>We review the column names again after renaming them, using the <code>colnames()</code> function can help.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sp500)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Stock"                 "Date"                  "StockName"            
 [4] "Sector"                "Industry"              "MarketCap"            
 [7] "Price"                 "Low52Wk"               "High52Wk"             
[10] "ROE"                   "ROA"                   "ROIC"                 
[13] "GrossMargin"           "OperatingMargin"       "NetMargin"            
[16] "PE"                    "PB"                    "EVEBITDA"             
[19] "EBITDA"                "EPS"                   "EBITDA_YOY"           
[22] "EBITDA_QYOY"           "EPS_YOY"               "EPS_QYOY"             
[25] "PFCF"                  "FCF"                   "FCF_QYOY"             
[28] "DebtToEquity"          "CurrentRatio"          "QuickRatio"           
[31] "DividendYield"         "DividendsPerShare_YOY" "PS"                   
[34] "Revenue_YOY"           "Revenue_QYOY"          "Rating"               
[37] "Security"              "GICSSector"            "GICSSubIndustry"      </code></pre>
</div>
</div>
</section>
<section id="understand-the-data-columns" class="level3">
<h3 class="anchored" data-anchor-id="understand-the-data-columns">Understand the Data Columns</h3>
<ol start="6" type="1">
<li>The complete data has 39 columns. Our next goal is to gain a deeper understanding of what the data columns mean. We reorganize the column names into eight tables, labeled Table 1a, 1b.. 1h.</li>
</ol>
<ol type="a">
<li>The column names described in Table 1a. concern basic <strong>Company Information</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1a: Data Columns giving basic Company Information
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stock</td>
<td style="text-align: left;">Stock Ticker (e.g. AAL)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">Date (e.g. "7/15/2023")</td>
</tr>
<tr class="odd">
<td style="text-align: left;">StockName</td>
<td style="text-align: left;">Name of the company (e.g "American Airlines Group, Inc.")</td>
</tr>
<tr class="even">
<td style="text-align: left;">GICSSector</td>
<td style="text-align: left;">Sector, as per GICS Classification</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GICSSubIndustry</td>
<td style="text-align: left;">Sub-Industry, as per GICS Classification</td>
</tr>
<tr class="even">
<td style="text-align: left;">MarketCap</td>
<td style="text-align: left;">Market capitalization of the company</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Price</td>
<td style="text-align: left;">Recent Stock Price</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="2" type="a">
<li>The column names described in Table 1b. are related to <strong>Technical Analysis</strong> of each stock, including the 52-Week High and Low prices.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1b: Data Columns related to Pricing and Technical Analysis
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Low52Wk</td>
<td style="text-align: left;">52-Week Low Price</td>
</tr>
<tr class="even">
<td style="text-align: left;">High52Wk</td>
<td style="text-align: left;">52-Week High Price</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rating</td>
<td style="text-align: left;">Technical Rating</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="3" type="a">
<li>The column names described in Table 1c. are related to the <strong>Profitability</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1c: Data Columns related to Profitability
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ROE</td>
<td style="text-align: left;">Return on Equity</td>
</tr>
<tr class="even">
<td style="text-align: left;">ROA</td>
<td style="text-align: left;">Return on Assets</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROIC</td>
<td style="text-align: left;">Return on Invested Capital</td>
</tr>
<tr class="even">
<td style="text-align: left;">GrossMargin</td>
<td style="text-align: left;">Gross Profit Margin</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OperatingMargin</td>
<td style="text-align: left;">Operating Profit Margin</td>
</tr>
<tr class="even">
<td style="text-align: left;">NetMargin</td>
<td style="text-align: left;">Net Profit Margin</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="4" type="a">
<li>The column names described in Table 1d are related to the <strong>Earnings</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1d: Data Columns related to Earnings
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PE</td>
<td style="text-align: left;">Price-to-Earnings Ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">PB</td>
<td style="text-align: left;">Price-to-Book Ratio</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EVEBITDA</td>
<td style="text-align: left;">Enterprise Value to EBITDA Ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">EBITDA</td>
<td style="text-align: left;">EBITDA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPS</td>
<td style="text-align: left;">Earnings per Share</td>
</tr>
<tr class="even">
<td style="text-align: left;">EBITDA_YOY</td>
<td style="text-align: left;">EBITDA Year-over-Year Growth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EBITDA_QYOY</td>
<td style="text-align: left;">EBITDA Quarterly Year-over-Year Growth</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPS_YOY</td>
<td style="text-align: left;">EPS Year-over-Year Growth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPS_QYOY</td>
<td style="text-align: left;">EPS Quarterly Year-over-Year Growth</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="5" type="a">
<li>The column names described in Table 1e are related to the <strong>Free Cash Flow</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1e: Data Columns related to Free Cash Flow
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PFCF</td>
<td style="text-align: left;">Price-to-Free Cash Flow</td>
</tr>
<tr class="even">
<td style="text-align: left;">FCF</td>
<td style="text-align: left;">Free Cash Flow</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FCF_QYOY</td>
<td style="text-align: left;">Free Cash Flow Quarterly Year-over-Year Growth</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="6" type="a">
<li>The column names described in Table 1f concern the <strong>Liquidity</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1f: Data Columns related to Liquidiy
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DebtToEquity</td>
<td style="text-align: left;">Debt-to-Equity Ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">CurrentRatio</td>
<td style="text-align: left;">Current Ratio</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QuickRatio</td>
<td style="text-align: left;">Quick Ratio</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="7" type="a">
<li>The column names described in Table 1g are related to the <strong>Revenue</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1g: Data Columns related to Revenue
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PS</td>
<td style="text-align: left;">Price-to-Sales Ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Revenue_YOY</td>
<td style="text-align: left;">Revenue Year-over-Year Growth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Revenue_QYOY</td>
<td style="text-align: left;">Revenue Quarterly Year-over-Year Growth</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="8" type="a">
<li>The column names described in Table 1h are related to the <strong>Dividends</strong> of each stock.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Table 1h: Data Columns related to Dividends
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">ColumnName</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DividendYield</td>
<td style="text-align: left;">Dividend Yield</td>
</tr>
<tr class="even">
<td style="text-align: left;">DividendsPerShare_YOY</td>
<td style="text-align: left;">Annual Dividends per Share Year-over-Year Growth</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="stock-ratings" class="level3">
<h3 class="anchored" data-anchor-id="stock-ratings">Stock Ratings</h3>
<ol type="1">
<li>In the data, the S&amp;P500 shares have Technical Ratings such as {Strong Buy, Buy, Neutral, Sell, Strong Sell}. Since each Stock has a unique Technical Rating, it makes sense to model the data column Rating as a factor() variable.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sp500<span class="sc">$</span>Rating <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(sp500<span class="sc">$</span>Rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>We confirm that Rating is now modelled as a factor variable, by running the <code>str()</code> function. We can use the <code>levels()</code> function to review the different levels it can take.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sp500<span class="sc">$</span>Rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 5 levels "Buy","Neutral",..: 1 1 3 4 1 3 3 4 2 3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sp500<span class="sc">$</span>Rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Buy"         "Neutral"     "Sell"        "Strong Buy"  "Strong Sell"</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>The <code>table()</code> function allows us to count how many stocks have each Rating.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sp500<span class="sc">$</span>Rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        Buy     Neutral        Sell  Strong Buy Strong Sell 
        192          51         178          58          24 </code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Thus, we can see how many stocks have ratings ranging from “Strong Sell” to “Strong Buy”. This completes our review of Rating.</li>
</ol>
</section>
<section id="analysis-of-gics-sectors-in-the-sp500" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-gics-sectors-in-the-sp500">Analysis of GICS Sectors in the S&amp;P500</h3>
<ul>
<li><p>The S&amp;P 500 comprises a wide array of sectors, reflecting the diverse American corporate landscape.</p></li>
<li><p>The data showcases the S&amp;P500 divided across 11 Sectors. The S&amp;P500 shares are divided into multiple Sectors. Each stock belongs to a unique sector. Thus, it makes sense to model Sector as a factor() variable.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sp500<span class="sc">$</span>GICSSector <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(sp500<span class="sc">$</span>GICSSector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>We confirm that <code>GICSSector</code> is now modelled as a factor variable, by running the <code>str()</code> function.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sp500<span class="sc">$</span>GICSSector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 11 levels "Communication Services",..: 6 7 8 6 2 6 5 8 8 8 ...</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>We can use the <code>levels()</code> function to review the different levels it can take.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sp500<span class="sc">$</span>GICSSector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Communication Services" "Consumer Discretionary" "Consumer Staples"      
 [4] "Energy"                 "Financials"             "Health Care"           
 [7] "Industrials"            "Information Technology" "Materials"             
[10] "Real Estate"            "Utilities"             </code></pre>
</div>
</div>
<ul>
<li>The S&amp;P500 consists of 503 stocks, divided across 11 sectors.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sp500, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">y =</span> GICSSector)) <span class="sc">+</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> GICSSector)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count))) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Stocks by GICS Sector"</span>, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"No. of Stocks"</span>, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"GICS Sector"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="17LiveCase01_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<ul>
<li>Thus, we can see how many stocks are part of each one of the 11 sectors. We can sum them to confirm that they add up to 503 stocks.</li>
</ul>
</section>
<section id="marketcap-by-gics-sector" class="level3">
<h3 class="anchored" data-anchor-id="marketcap-by-gics-sector">MarketCap by GICS Sector</h3>
<ol type="1">
<li>We review the Market Cap of S&amp;P500 stocks across GICS Sectors. We summarize the total Market Cap for each GICS Sector, using the following code.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>MarketCapbySector <span class="ot">&lt;-</span> sp500 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Market_Cap_Billions =</span> <span class="fu">round</span>(MarketCap<span class="sc">/</span><span class="dv">1000000000</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GICSSector) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">MarketCapBillions =</span> <span class="fu">sum</span>(Market_Cap_Billions, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>MarketCapBillions)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Next, we create a row, to display the total across all GICS Sectors.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a row for the grand total</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>summary_row <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">GICSSector =</span> <span class="st">"Total"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">MarketCapBillions =</span> <span class="fu">sum</span>(MarketCapbySector<span class="sc">$</span>MarketCapBillions)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>summary_row</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  GICSSector MarketCapBillions
  &lt;chr&gt;                  &lt;dbl&gt;
1 Total                 43733.</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Finally, we append this row to the bottom of the summary table and display it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Append the summary row to the result</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>MarketCapbySector <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(MarketCapbySector, summary_row)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Render the table</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>MarketCapbySector <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"Market Capitalization (Billions of USD) of S&amp;P500 by GICS Sector"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Market Capitalization (Billions of USD) of S&amp;P500 by GICS Sector</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">GICSSector</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MarketCapBillions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Information Technology</td>
<td style="text-align: right;">11462.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Financials</td>
<td style="text-align: right;">5734.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Communication Services</td>
<td style="text-align: right;">5642.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Health Care</td>
<td style="text-align: right;">5323.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Consumer Discretionary</td>
<td style="text-align: right;">4596.22</td>
</tr>
<tr class="even">
<td style="text-align: left;">Industrials</td>
<td style="text-align: right;">3598.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Consumer Staples</td>
<td style="text-align: right;">2819.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Energy</td>
<td style="text-align: right;">1622.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Real Estate</td>
<td style="text-align: right;">1009.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">Materials</td>
<td style="text-align: right;">969.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Utilities</td>
<td style="text-align: right;">953.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">43732.80</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol start="4" type="1">
<li>This table gives us the breakdown of the Market Cap of the different stocks in the S&amp;P500 across different GICS Sectors. We note that the Information Technology and Utilities sectors have the relatively highest and lowest Market Cap respectively. We also note that the entire S&amp;P500 has a combined Market Cap of the S&amp;P 500, as of 5Jan2024, is 43732.8 Billion USD.</li>
</ol>
</section>
</section>
<section id="summary-of-chapter-exploring-sp500-data" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-chapter-exploring-sp500-data">Summary of Chapter – Exploring S&amp;P500 Data</h2>
<p>This chapter explores the S&amp;P500, a significant stock market index encompassing 500 major publicly traded companies in the U.S. The chapter introduces the index’s role as a benchmark for assessing the overall health and performance of the U.S. stock market, maintained by S&amp;P Dow Jones Indices.</p>
<p>This chapter guides readers through the intricacies of exploring S&amp;P500 data, employing practical examples and R code to foster a deeper understanding of the breakdown of the S&amp;P 500 across different GICS Sectors. Further exploration is encouraged with a wealth of references for continued learning and analysis.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p><strong>S&amp;P 500</strong></p>
<p>[1] https://www.investopedia.com/terms/s/sp500.asp</p>
<p>[2] S&amp;P Global: S&amp;P Global. (n.d.). S&amp;P 500. Retrieved September 14, 2023, from https://www.spglobal.com/spdji/en/indices/equity/sp-500/</p>
<p>MarketWatch: MarketWatch. (n.d.). S&amp;P 500 Index. Retrieved September 14, 2023, from https://www.marketwatch.com/investing/index/spx</p>
<p>Bloomberg: Bloomberg. (n.d.). S&amp;P 500 Index (SPX:IND). Retrieved September 14, 2023, from https://www.bloomberg.com/quote/SPX:IND</p>
<p>[3] TradingView.com <a href="https://www.tradingview.com/screener/" class="uri">https://www.tradingview.com/screener/</a></p>
<p>[4] GICS: Global Industry Classification Standard: <a href="https://www.spglobal.com/spdji/en/landing/topic/gics/" class="uri">https://www.spglobal.com/spdji/en/landing/topic/gics/</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.qatar.cmu.edu/directory/sameer-mathur/">Sameer Mathur</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&amp;ouid=100224206438187222136&amp;rtpof=true&amp;sd=true">Aryeman Gupta Mathur</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>